### ISSUE TITLE
Zbyt mało pytań

### ISSUE THREAD

**Issue by jqdq** [urzyk/bingo#1]
Po dwóch rozgrywkach wszystkie hasła się wyczerpują i zdecydowanie odbiera to chęć do dalszego korzystania z programu

**Comment by jqdq** [comment]
Dobra w sumie to teraz faktycznie sprawdziłem na kod i program w ogóle nie działa przez brak pytań xdd

**Comment by jqdq** [comment]
i wcale nie zmieniłem "haseł" na "pytań", bo myślałem, że bingo = wisielec

**Comment by urzyk** [comment]
NIKT NIE PYTAŁ!!!!

**Comment by jqdq** [comment]
fair enough
